name: dart_test_utils
description: A package containing dart test utils.
version: 0.0.1
homepage: https://github.com/defuncart/dart_test_utils
repository: https://github.com/defuncart/dart_test_utils
issue_tracker: https://github.com/defuncart/dart_test_utils/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  args: ^2.4.2
  path: ^1.8.3

dev_dependencies:
  test:
  lints:
